name: model_test_generator
description: Automatically generate test code for Dart classes.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  analyzer: ^6.3.0
  mason: ^0.1.0-dev.51
  meta: ^1.11.0

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
