name: model_test_generator
description: Automatically generate test code for Dart classes.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  mason: ^0.1.0-dev.50
  meta: ^1.9.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
